In [24]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [25]:
df = pd.read_csv('ViewingActivity.csv')
df.head()

,Duration,Start Time,Profile Name,Country,Bookmark,Latest Bookmark,Supplemental Video Type,Attributes,Device Type,Title
0,00:10:42,2026-02-01 14:19:35,João Vitor,BR (Brazil),00:11:25,00:11:25,NaN,Autoplayed: user action: None;,Apple iPhone 15 iPhone,Wakfu: Temporada 2: Kriss Krass (episódio 10)
1,00:23:30,2026-02-01 13:52:54,João Vitor,BR (Brazil),00:22:12,00:22:12,NaN,NaN,Apple iPhone 15 iPhone,Wakfu: Temporada 2: O mundo de Rushu (episódio 9)
2,00:05:09,2026-02-01 13:48:13,João Vitor,BR (Brazil),00:21:54,00:21:54,NaN,NaN,Apple iPhone 15 iPhone,Wakfu: Temporada 2: O cavaleiro justiceiro (ep...
3,00:15:48,2026-01-31 17:18:08,João Vitor,BR (Brazil),00:16:44,Not latest view,NaN,NaN,Apple iPhone 15 iPhone,Wakfu: Temporada 2: O cavaleiro justiceiro (ep...
4,00:00:44,2026-01-31 17:15:02,João Vitor,BR (Brazil),00:00:45,Not latest view,NaN,Autoplayed: user action: None;,Apple iPhone 15 iPhone,Wakfu: Temporada 2: O cavaleiro justiceiro (ep...

In [26]:
#eliminar colunas desnecessárias
df.drop(["Profile Name", "Attributes", "Supplemental Video Type", "Device Type",
"Bookmark", "Latest Bookmark", "Country"], axis=1, inplace=True)
df.head()

,Duration,Start Time,Title
0,00:10:42,2026-02-01 14:19:35,Wakfu: Temporada 2: Kriss Krass (episódio 10)
1,00:23:30,2026-02-01 13:52:54,Wakfu: Temporada 2: O mundo de Rushu (episódio 9)
2,00:05:09,2026-02-01 13:48:13,Wakfu: Temporada 2: O cavaleiro justiceiro (ep...
3,00:15:48,2026-01-31 17:18:08,Wakfu: Temporada 2: O cavaleiro justiceiro (ep...
4,00:00:44,2026-01-31 17:15:02,Wakfu: Temporada 2: O cavaleiro justiceiro (ep...

In [27]:
df.columns = ['Duration','Start_Time', 'Title']
df.isna().values.any()
df.dtypes

Duration      object
Start_Time    object
Title         object
dtype: object

In [28]:
# Convertendo a coluna 'Date' para datetime
df['Start_Time'] = pd.to_datetime(df['Start_Time'], utc=True)
df.dtypes

Duration                   object
Start_Time    datetime64[ns, UTC]
Title                      object
dtype: object

In [29]:
# transformar Date em índice
df = df.set_index('Start_Time')

# converter o fuso horário
df.index = df.index.tz_convert('America/Sao_Paulo')

# se quiser voltar Date para coluna
df = df.reset_index()

df.head()

,Start_Time,Duration,Title
0,2026-02-01 11:19:35-03:00,00:10:42,Wakfu: Temporada 2: Kriss Krass (episódio 10)
1,2026-02-01 10:52:54-03:00,00:23:30,Wakfu: Temporada 2: O mundo de Rushu (episódio 9)
2,2026-02-01 10:48:13-03:00,00:05:09,Wakfu: Temporada 2: O cavaleiro justiceiro (ep...
3,2026-01-31 14:18:08-03:00,00:15:48,Wakfu: Temporada 2: O cavaleiro justiceiro (ep...
4,2026-01-31 14:15:02-03:00,00:00:44,Wakfu: Temporada 2: O cavaleiro justiceiro (ep...

In [30]:
df['Duration'] = pd.to_timedelta(df['Duration'])
df.dtypes

Start_Time    datetime64[ns, America/Sao_Paulo]
Duration                        timedelta64[ns]
Title                                    object
dtype: object

In [31]:
#criando novas colunar 'Season' e 'Episode' utilizando a coluna 'Title'
df[['Title_Name', 'Season', 'Episode']] = df['Title'].str.split(': ',n=2, expand=True)

df.drop('Title', axis=1, inplace=True)

df.head()

,Start_Time,Duration,Title_Name,Season,Episode
0,2026-02-01 11:19:35-03:00,0 days 00:10:42,Wakfu,Temporada 2,Kriss Krass (episódio 10)
1,2026-02-01 10:52:54-03:00,0 days 00:23:30,Wakfu,Temporada 2,O mundo de Rushu (episódio 9)
2,2026-02-01 10:48:13-03:00,0 days 00:05:09,Wakfu,Temporada 2,O cavaleiro justiceiro (episódio 8)
3,2026-01-31 14:18:08-03:00,0 days 00:15:48,Wakfu,Temporada 2,O cavaleiro justiceiro (episódio 8)
4,2026-01-31 14:15:02-03:00,0 days 00:00:44,Wakfu,Temporada 2,O cavaleiro justiceiro (episódio 8)

In [32]:
#criando novas colunas de 'Mês' e 'Hora' utilizando a coluna 'Start_Time'
df['Mês'] = df['Start_Time'].dt.weekday

df['Hora'] = df['Start_Time'].dt.hour

df.head()

,Start_Time,Duration,Title_Name,Season,Episode,Mês,Hora
0,2026-02-01 11:19:35-03:00,0 days 00:10:42,Wakfu,Temporada 2,Kriss Krass (episódio 10),6,11
1,2026-02-01 10:52:54-03:00,0 days 00:23:30,Wakfu,Temporada 2,O mundo de Rushu (episódio 9),6,10
2,2026-02-01 10:48:13-03:00,0 days 00:05:09,Wakfu,Temporada 2,O cavaleiro justiceiro (episódio 8),6,10
3,2026-01-31 14:18:08-03:00,0 days 00:15:48,Wakfu,Temporada 2,O cavaleiro justiceiro (episódio 8),5,14
4,2026-01-31 14:15:02-03:00,0 days 00:00:44,Wakfu,Temporada 2,O cavaleiro justiceiro (episódio 8),5,14

In [33]:
#Quantidade de plays em cada serie
df['Title_Name'].value_counts()

Title_Name
Captain Tsubasa                  144
Masha e o Urso                   143
Você                             141
O Show da Luna!                  133
A Casa Mágica da Gabby           121
                                ...
Jogo da Lava                       1
Herança Roubada                    1
Headspace - Guia para Relaxar      1
Barbie                             1
A Série Mestre Pokémon             1
Name: count, Length: 503, dtype: int64

In [34]:
#top 10 series mais assistidas
top_10_series = df.groupby(['Title_Name']).agg({'Duration': 'sum'}).sort_values(by = 'Duration', ascending=False).head(10)
top_10_series.head(10)

                              Duration
Title_Name
Stranger Things        1 days 21:12:15
Você                   1 days 03:26:54
Round 6                1 days 03:15:09
Masha e o Urso         1 days 01:47:47
A Casa Mágica da Gabby 1 days 01:33:04
Captain Tsubasa        0 days 21:49:08
Little Angel           0 days 19:24:15
Gilmore Girls          0 days 18:42:36
O Show da Luna!        0 days 17:02:28
CoComelon              0 days 13:43:00

In [35]:
#top 10 filmes mais assistidos
top_10_filmes = df[df['Season'].isna()].groupby(['Title_Name']).agg({'Duration': 'sum'}).sort_values(by = 'Duration', ascending=False).head(10)
top_10_filmes.head(10)

                             Duration
Title_Name
Frankenstein          0 days 05:00:19
Guerreiras do K-Pop   0 days 04:27:05
O Poderoso Chefinho   0 days 04:05:45
O Mundo Depois de Nós 0 days 02:46:47
Furioza 2             0 days 02:40:53
Através das Sombras   0 days 02:19:54
Bandido               0 days 02:12:18
A Sociedade da Neve   0 days 02:12:14
Corações de Ferro     0 days 02:09:17
Rebel Ridge           0 days 02:04:21

In [36]:
#Quantidade totais de midia assistida
total_duration = df['Duration'].sum()
print(f'Tempo total assistido: {total_duration}')

#Quantidade de midia assistida por mês
df['Month'] = df['Start_Time'].dt.month
media_por_mes = df.groupby('Month')['Title_Name'].nunique()
print(media_por_mes)

#Quantidade totais de midias assistidas
total_titles = df['Title_Name'].nunique()
print(f'Total de títulos assistidos: {total_titles}')

Tempo total assistido: 23 days 14:16:57
Month
1      90
2      39
3      66
4      53
5      75
6      73
7     139
8      58
9      53
10    117
11     90
12    112
Name: Title_Name, dtype: int64
Total de títulos assistidos: 503